"use strict";
const assert=require("node:assert/strict");
const {detectBusinessAnomalies}=require("./anomaly-detection");
const FinanceExpenses=require("./finance-expenses");
const MonthlyProfitForecast=require("./monthly-profit-forecast");
const fridays=["2026-06-05","2026-06-12","2026-06-19","2026-06-26"].map(date=>({date,sales:200000,patients:20,expense:100000}));
let result=detectBusinessAnomalies({entries:[...fridays,{date:"2026-07-03",sales:140000,patients:10,expense:160000}],clinic:{}},{today:"2026-07-03",hour:18});
assert.equal(result.find(x=>x.metric==="客単価").level,"normal");
assert.equal(result.find(x=>x.metric==="来院件数").level,"danger");
assert.equal(result.find(x=>x.metric==="日商").level,"danger");
assert.equal(result.some(x=>x.metric==="利益率"),false,"daily anomalies exclude profit margin");
assert.equal(result.some(x=>x.metric==="総支出"),false,"daily anomalies exclude total expenses");
assert.equal(JSON.stringify(result).includes("支出"),false,"daily shadow comments do not mention expenses");
const monthlyFinance=FinanceExpenses.resolve({hospitalCashExpense:160000,depreciationExpense:10000});
assert.equal(monthlyFinance.hospitalCashExpense,160000,"finance retains total expenses");
const monthlyAnalysis=MonthlyProfitForecast.calculate({businessDays:20,scheduledBusinessDays:20,currentSales:140000,currentExpense:monthlyFinance.hospitalCashExpense,fixedExpense:monthlyFinance.hospitalCashExpense,currentProfit:-20000,historicalMonths:[{sales:200000,expense:100000}]});
assert.equal(monthlyAnalysis.projectedExpense,160000,"monthly analysis retains total expenses");
assert.equal(monthlyAnalysis.historicalRate,.5,"monthly analysis still calculates profit margin");
assert.deepEqual(detectBusinessAnomalies({entries:fridays},{today:"2026-07-03",hour:18}),[],"missing current input");
assert.deepEqual(detectBusinessAnomalies({entries:[...fridays,{date:"2026-07-03",sales:1,patients:1}]},{today:"2026-07-03",hour:8}),[],"before opening");
assert.deepEqual(detectBusinessAnomalies({entries:[...fridays.slice(0,2),{date:"2026-07-03",sales:1,patients:1}]},{today:"2026-07-03",hour:18}),[],"fewer than three comparisons");
assert.deepEqual(detectBusinessAnomalies({entries:[{date:"2026-06-08",sales:10,patients:1},{date:"2026-06-15",sales:10,patients:1},{date:"2026-06-22",sales:10,patients:1},{date:"2026-06-29",sales:10,patients:1}]},{today:"2026-06-29",hour:18}),[],"Monday closure");
console.log("business anomaly tests: 14 checks passed");
