(()=>{"use strict";
const KEY="keitaDashboardV41";
const blank={entries:[],monthSettings:{},finance:{balance:0,loan:0,lease:0,fixedCost:0,repayment:0},memo:""};
let data=load();
const $=id=>document.getElementById(id);
const n=id=>Math.max(0,Number($(id).value)||0);
const yen=v=>`${Math.round(Number(v)||0).toLocaleString("ja-JP")}円`;
const pct=v=>`${(Number(v)||0).toFixed(1)}%`;
const iso=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const monthNow=()=>iso().slice(0,7);
function load(){try{return {...structuredClone(blank),...(JSON.parse(localStorage.getItem(KEY))||{})}}catch{return structuredClone(blank)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1600)}
function totals(entries){const t=entries.reduce((a,e)=>{for(const k of["sales","expense","patients","surgeries","checkups","trimmings","emergencies"])a[k]+=Number(e[k])||0;return a},{sales:0,expense:0,patients:0,surgeries:0,checkups:0,trimmings:0,emergencies:0});t.profit=t.sales-t.expense;t.rate=t.sales?t.profit/t.sales*100:0;t.unit=t.patients?t.sales/t.patients:0;return t}
function preview(){const sales=n("cashSales")+n("cardSales")+n("otherSales"),patients=n("dogs")+n("cats"),profit=sales-n("expense");$("salesView").textContent=yen(sales);$("patientsView").textContent=`${patients}件`;$("profitView").textContent=yen(profit);$("rateView").textContent=pct(sales?profit/sales*100:0);$("unitView").textContent=yen(patients?sales/patients:0);$("speciesView").textContent=`${n("dogs")}：${n("cats")}`}
function saveToday(){const date=$("entryDate").value;if(!date)return toast("日付を入力してください");const cash=n("cashSales"),card=n("cardSales"),other=n("otherSales"),dogs=n("dogs"),cats=n("cats");const e={date,cashSales:cash,cardSales:card,otherSales:other,sales:cash+card+other,expense:n("expense"),dogs,cats,patients:dogs+cats,surgeries:n("surgeries"),checkups:n("checkups"),trimmings:n("trimmings"),emergencies:n("emergencies"),note:$("note").value.trim()};const i=data.entries.findIndex(x=>x.date===date);i>=0?data.entries[i]=e:data.entries.push(e);data.entries.sort((a,b)=>a.date.localeCompare(b.date));save();render();toast(i>=0?"更新しました":"保存しました")}
function clearForm(){["cashSales","cardSales","otherSales","expense","dogs","cats","surgeries","checkups","trimmings","emergencies","note"].forEach(id=>$(id).value="");$("entryDate").value=iso();preview()}
function recent(){const tb=$("recentEntries");tb.innerHTML="";const list=[...data.entries].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,12);if(!list.length){tb.innerHTML='<tr><td colspan="6">まだ記録がありません。</td></tr>';return}for(const e of list){const tr=document.createElement("tr");tr.innerHTML=`<td>${e.date}</td><td>${yen(e.sales)}</td><td>${e.dogs||0}</td><td>${e.cats||0}</td><td>${yen(e.patients?e.sales/e.patients:0)}</td><td><button data-del="${e.date}" class="danger">削除</button></td>`;tb.appendChild(tr)}tb.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{if(confirm(`${b.dataset.del}を削除しますか？`)){data.entries=data.entries.filter(e=>e.date!==b.dataset.del);save();render()}})}
function renderMonth(){const m=$("monthPicker").value||monthNow(),s=data.monthSettings[m]||{target:4500000,businessDays:26};$("monthlyTarget").value=s.target;$("businessDays").value=s.businessDays;const t=totals(data.entries.filter(e=>e.date.startsWith(m))),target=Number(s.target)||0,days=Math.max(1,Number(s.businessDays)||26),used=new Set(data.entries.filter(e=>e.date.startsWith(m)).map(e=>e.date)).size,left=Math.max(0,days-used),remain=Math.max(0,target-t.sales),need=left?remain/left:remain,progress=target?t.sales/target*100:0;for(const [id,val] of Object.entries({monthSales:yen(t.sales),monthExpense:yen(t.expense),monthProfit:yen(t.profit),monthRate:pct(t.rate),monthPatients:`${t.patients}件`,monthUnit:yen(t.unit),monthSurgeries:`${t.surgeries}件`,monthCheckups:`${t.checkups}件`,monthTrimmings:`${t.trimmings}件`,monthEmergencies:`${t.emergencies}件`,monthProgress:pct(progress),needSales:yen(need)}))$(id).textContent=val;$("progressBar").style.width=`${Math.min(100,progress)}%`;$("monthComment").textContent=progress>=100?"目標を達成しています。":`残り${left}営業日。1日あたり${yen(need)}が目安です。`}
function saveMonth(){const m=$("monthPicker").value||monthNow();data.monthSettings[m]={target:n("monthlyTarget"),businessDays:Math.max(1,n("businessDays")||26)};save();renderMonth();toast("目標を保存しました")}
function years(){const ys=new Set(data.entries.map(e=>e.date.slice(0,4)));ys.add(String(new Date().getFullYear()));$("yearPicker").innerHTML=[...ys].sort().reverse().map(y=>`<option>${y}</option>`).join("")}
function renderYear(){const y=$("yearPicker").value||String(new Date().getFullYear()),rows=[];for(let m=1;m<=12;m++)rows.push(totals(data.entries.filter(e=>e.date.startsWith(`${y}-${String(m).padStart(2,"0")}`))));const t=totals(data.entries.filter(e=>e.date.startsWith(y))),active=rows.filter(r=>r.sales).length,max=Math.max(1,...rows.map(r=>r.sales));$("yearSales").textContent=yen(t.sales);$("yearProfit").textContent=yen(t.profit);$("yearPatients").textContent=`${t.patients}件`;$("yearAverage").textContent=yen(active?t.sales/active:0);$("chart").innerHTML=rows.map((r,i)=>`<div class="bar"><i style="height:${Math.max(r.sales?3:0,r.sales/max*100)}%"></i><b>${i+1}月</b></div>`).join("")}
function renderFinance(){const f=data.finance||blank.finance;for(const k in f)if($(k))$(k).value=f[k]||"";$("netPosition").textContent=yen((f.balance||0)-(f.loan||0));$("fixedOutflow").textContent=yen((f.lease||0)+(f.fixedCost||0)+(f.repayment||0))}
function saveFinance(){data.finance={balance:n("balance"),loan:n("loan"),lease:n("lease"),fixedCost:n("fixedCost"),repayment:n("repayment")};save();renderFinance();toast("保存しました")}
function download(name,text,type){const a=document.createElement("a"),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function exportJson(){download(`dashboard-backup-${iso()}.json`,JSON.stringify(data,null,2),"application/json")}
function exportCsv(){const h=["date","cashSales","cardSales","otherSales","sales","expense","dogs","cats","patients","surgeries","checkups","trimmings","emergencies","note"],q=v=>`"${String(v??"").replaceAll('"','""')}"`,rows=data.entries.map(e=>h.map(k=>q(e[k])).join(","));download(`dashboard-${iso()}.csv`,"\uFEFF"+[h.join(","),...rows].join("\n"),"text/csv")}
function render(){recent();renderMonth();years();renderYear();renderFinance();$("memoText").value=data.memo||""}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===b.dataset.page));if(b.dataset.page==="month")renderMonth();if(b.dataset.page==="year"){years();renderYear()}});["cashSales","cardSales","otherSales","expense","dogs","cats"].forEach(id=>$(id).oninput=preview);$("saveToday").onclick=saveToday;$("clearToday").onclick=clearForm;$("monthPicker").onchange=renderMonth;$("saveMonthSettings").onclick=saveMonth;$("yearPicker").onchange=renderYear;$("saveFinance").onclick=saveFinance;$("memoText").oninput=()=>{data.memo=$("memoText").value;save()};$("exportJson").onclick=exportJson;$("exportCsv").onclick=exportCsv;$("importJson").onchange=async e=>{try{data=JSON.parse(await e.target.files[0].text());save();render();toast("復元しました")}catch{alert("読み込めませんでした")}};$("deleteAll").onclick=()=>{if(confirm("全データを削除しますか？")){data=structuredClone(blank);save();clearForm();render()}};
$("todayDate").textContent=new Date().toLocaleDateString("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"short"});$("entryDate").value=iso();$("monthPicker").value=monthNow();clearForm();render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
})();