(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.BusinessHealthScore=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
 "use strict";
 const MIN_LEARNING_DAYS=20,MIN_START_DAYS=50,HISTORY_LIMIT=730;
 const num=value=>Number(value)||0,clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
 const band=(value,levels)=>{for(const [minimum,points] of levels)if(value>=minimum)return points;return 0};
 const profitPoints=value=>band(num(value),[[40,25],[35,20],[30,15],[25,10],[20,5]]),salesPoints=value=>band(num(value),[[100,20],[95,18],[90,16],[80,12],[70,8]]),unitPoints=value=>band(num(value),[[10,20],[5,18],[0,15],[-5,10],[-10,5]]);
 const revisitPoints=value=>Math.round(clamp(num(value)/70*10,0,10)),workloadPoints=value=>Math.round(clamp((100-num(value))/50*15,0,15)),successPoints=value=>band(num(value),[[90,10],[80,8],[70,6],[60,4]]);
 function grade(score){const value=num(score);return value>=90?{label:"Excellent",tone:"excellent"}:value>=80?{label:"Good",tone:"good"}:value>=70?{label:"Stable",tone:"stable"}:value>=60?{label:"Attention",tone:"attention"}:{label:"Action Required",tone:"action"}}
 function opportunities(components={}){return [{key:"revisit",label:"再診予約",gap:10-num(components.revisitRate)},{key:"imaging",label:"画像検査",gap:10-num(components.successPattern)},{key:"checkup",label:"健診",gap:15-num(components.doctorWorkload)},{key:"unitPrice",label:"客単価",gap:20-num(components.unitPrice)}].map(item=>({...item,stars:clamp(Math.ceil(item.gap/2),1,5)})).sort((a,b)=>b.gap-a.gap)}
 function calculate(input={}){const businessDays=Math.max(0,Math.trunc(num(input.businessDays))),unitChange=num(input.normalUnitPrice)?(num(input.unitPrice)/num(input.normalUnitPrice)-1)*100:0,components={profitRate:profitPoints(input.profitRate),salesAchievement:salesPoints(input.salesAchievement),unitPrice:unitPoints(unitChange),revisitRate:revisitPoints(input.revisitRate),doctorWorkload:workloadPoints(input.doctorWorkload),successPattern:successPoints(input.successPatternMatch)},previewScore=Object.values(components).reduce((sum,value)=>sum+value,0),ready=businessDays>=MIN_START_DAYS;return {score:ready?previewScore:null,previewScore,ready,status:businessDays<MIN_LEARNING_DAYS?"学習中":ready?"算出中":"学習を継続中",businessDays,requiredDays:MIN_START_DAYS,remainingDays:Math.max(0,MIN_START_DAYS-businessDays),components,metrics:{...input,unitPriceChange:unitChange},grade:grade(previewScore),opportunities:opportunities(components)}}
 function normalizeHistory(value){return (Array.isArray(value)?value:[]).filter(item=>item&&/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&Number.isFinite(Number(item.score))).map(item=>({...item,score:clamp(Math.round(num(item.score)),0,100)})).sort((a,b)=>a.date.localeCompare(b.date)).slice(-HISTORY_LIMIT)}
 function updateHistory(history,result,date){const current=normalizeHistory(history).filter(item=>item.date!==date);return result?.ready?normalizeHistory([...current,{date,score:result.score,grade:result.grade.label}]):current}
 function summary(history,month){const rows=normalizeHistory(history).filter(item=>!month||item.date.startsWith(month)),scores=rows.map(item=>item.score);if(!scores.length)return {count:0,average:null,highest:null,lowest:null,improvement:null};return {count:scores.length,average:Math.round(scores.reduce((a,b)=>a+b,0)/scores.length),highest:Math.max(...scores),lowest:Math.min(...scores),improvement:scores.at(-1)-scores[0]}}
 function displayScore(result,history,date,isClosed){const current=Number(result?.score),previous=normalizeHistory(history).filter(item=>item.date<date).at(-1);if(isClosed&&previous)return {...result,score:previous.score,grade:grade(previous.score),asOf:previous.date};return {...result,score:Number.isFinite(current)?current:result?.score,asOf:null}}
 return {MIN_LEARNING_DAYS,MIN_START_DAYS,calculate,grade,normalizeHistory,updateHistory,summary,displayScore};
});
