const test=require("node:test"),assert=require("node:assert/strict"),Simulator=require("./business-simulator");
const source={entries:Array.from({length:20},(_,i)=>({date:`2026-07-${String(i+1).padStart(2,"0")}`,sales:200000,patients:20,newPatients:3,checkups:2,surgeries:1,clinical:{xrays:3,ultrasounds:1,bloodTests:5,preventive:2}})),finance:{monthlyExpense:3500000},successLibrary:[{id:"imaging"}],forecastHistory:[{}]};
const plannerSource={...source,finance:{monthlyExpense:4616667}};
test("simulation reacts immediately and ranks improvements",()=>{const result=Simulator.simulate(source,{imagingRate:12,checkups:8},20000000);assert.ok(result.delta>0);assert.ok(result.annualProfit>result.current.annualProfit);assert.equal(result.ranking[0].key,"imagingRate");assert.ok(result.probability>=35&&result.probability<=96)});
test("reverse planner changes KPIs and respects dynamic percentage limits",()=>{const plan=Simulator.reversePlan(plannerSource,20000000),limits=Simulator.improvementLimits(plannerSource);assert.ok(Object.values(plan.changes).some(Boolean));Object.entries(plan.changes).forEach(([key,value])=>assert.ok(value>=0&&value<=limits[key]));assert.ok(plan.result.annualProfit>plan.result.current.annualProfit)});
test("reverse planner handles all goals and reports unreachable targets",()=>{for(const goal of [10000000,15000000,20000000]){const plan=Simulator.reversePlan(plannerSource,goal);assert.ok(["achieved","unreachable"].includes(plan.status));assert.ok(Object.values(plan.changes).some(Boolean))}assert.equal(Simulator.reversePlan(plannerSource,100000000).status,"unreachable")});
test("a 97% revisit rate can only improve by 3%",()=>{const nearCeiling={...plannerSource,entries:source.entries.map(entry=>({...entry,patients:100,newPatients:3}))};assert.equal(Simulator.improvementLimits(nearCeiling).revisitRate,3);const plan=Simulator.reversePlan(nearCeiling,100000000);assert.equal(plan.changes.revisitRate,3);assert.ok(plan.result.current.revisitRate+plan.changes.revisitRate<=100)});
test("night learning saves once after 18:00",()=>{const first=Simulator.updateAtNight({...source,businessSimulator:{changes:{checkups:5}}},{now:"2026-08-16T18:05:00Z"});assert.equal(first.saved,true);const again=Simulator.updateAtNight({...source,simulationHistory:first.simulationHistory},{now:"2026-08-16T20:00:00Z"});assert.equal(again.saved,false)});
test("empty data remains finite and usable",()=>{const result=Simulator.simulate({},{});assert.ok(Number.isFinite(result.annualProfit));assert.match(result.dataStatus,/学習データ/)});
