"use strict";
const assert=require("node:assert/strict");
const {FIELDS,LEGACY_FIELDS,normalizeClinical,calculateRevisits,getClinicalRates}=require("./clinical-data");
assert.deepEqual(FIELDS,["bloodTests","xrays","ultrasounds","preventive"]);
assert.deepEqual(LEGACY_FIELDS,["bloodTests","xrays","ultrasounds","preventive","revisits"]);
const clinical=normalizeClinical({bloodTests:5,xrays:2,ultrasounds:3,revisits:16,preventive:4});
assert.equal(clinical.revisits,16,"legacy revisit remains readable");
assert.equal(normalizeClinical({bloodTests:0}).bloodTests,0);assert.equal(normalizeClinical({bloodTests:""}).bloodTests,null);
assert.equal(normalizeClinical({bloodTests:120}).bloodTests,99);assert.equal(normalizeClinical({preventive:-4}).preventive,0);
assert.equal(calculateRevisits({patients:20,newPatients:3}),17);assert.equal(calculateRevisits({patients:10,newPatients:0}),10);
for(const entry of [{patients:0,newPatients:0},{patients:"",newPatients:3},{patients:10,newPatients:""},{patients:2,newPatients:3}])assert.equal(calculateRevisits(entry),null);
let rates=getClinicalRates({patients:20,newPatients:3,surgeries:2,clinical});
assert.deepEqual(rates,{bloodTests:25,xrays:10,ultrasounds:15,preventive:20,revisits:85,newPatients:15,surgeries:10});
rates=getClinicalRates({patients:20,newPatients:null,clinical:{revisits:16}});assert.equal(rates.revisits,80,"legacy fallback");
assert.equal(getClinicalRates({patients:20,newPatients:3,clinical:{revisits:2}}).revisits,85,"calculation is canonical");
assert.equal(getClinicalRates({patients:2,newPatients:3,clinical:{revisits:1}}).revisits,null,"invalid canonical values never fall back to a misleading legacy count");
for(const patients of [0,"",null,-1,"invalid"])assert.ok(Object.values(getClinicalRates({patients,newPatients:3,clinical})).every(value=>value===null));
console.log("clinical data tests: four fields, safe automatic revisits, rates, and legacy compatibility passed");
