(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.ClinicalTags=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
 "use strict";
 const GROUPS=[{label:"患者構成",tags:[["new_patient_high","新患多い"],["repeat_patient_high","再診多い"],["severe_case_high","重症例多い"],["mild_case_high","軽症例多い"]]},{label:"診療内容",tags:[["exam_proposal_high","検査提案多い"],["exam_proposal_low","検査提案少なめ"],["checkup_high","健診多い"],["prevention_high","予防多い"],["surgery_day","手術日"]]},{label:"診療環境",tags:[["reservation_high","予約多い"],["reservation_low","予約少ない"],["staff_shortage","スタッフ不足"],["workload_high","診療負荷高い"]]}];
 const TAGS=Object.fromEntries(GROUPS.flatMap(group=>group.tags));
 const normalize=value=>[...new Set((Array.isArray(value)?value:[]).filter(id=>Object.hasOwn(TAGS,id)))];
 const n=value=>Number(value)||0,clinical=(entry,...keys)=>keys.reduce((sum,key)=>sum+n(entry?.[key]??entry?.clinical?.[key]),0);
 function metrics(entry){const patients=n(entry.patients),sales=n(entry.sales),rate=value=>patients?value/patients*100:0;return {unitPrice:patients?sales/patients:0,imagingRate:rate(clinical(entry,"imaging","xrays","ultrasounds")),bloodRate:rate(clinical(entry,"bloodTests")),checkupRate:rate(clinical(entry,"checkups","healthChecks")),managementScore:Number(entry.businessHealthScore??entry.managementScore)||0}}
 const average=(rows,key)=>rows.length?rows.reduce((sum,row)=>sum+metrics(row)[key],0)/rows.length:0;
 function analyze(entries,{month=null}={}){const rows=(Array.isArray(entries)?entries:[]).filter(e=>e&&(!month||String(e.date||"").startsWith(month))&&n(e.patients)>0),result=[];for(const [id,label] of Object.entries(TAGS)){const tagged=rows.filter(e=>normalize(e.clinicalTags).includes(id)),other=rows.filter(e=>!normalize(e.clinicalTags).includes(id));if(tagged.length<3)continue;const confidence=tagged.length>=10?"比較的安定":tagged.length>=5?"傾向あり":"参考傾向",keys=["unitPrice","imagingRate","bloodRate","checkupRate","managementScore"],differences=keys.map(key=>({key,tagged:average(tagged,key),other:average(other,key),delta:average(tagged,key)-average(other,key)})).filter(x=>other.length&&Math.abs(x.delta)>0.01).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta));result.push({id,label,sampleDays:tagged.length,comparisonDays:other.length,confidence,differences})}return result.sort((a,b)=>b.sampleDays-a.sampleDays)}
 function sentence(item){const names={unitPrice:"客単価",imagingRate:"画像検査率",bloodRate:"血液検査率",checkupRate:"健康診断率",managementScore:"診療経営スコア"},difference=item?.differences?.[0];return difference?`「${item.label}」と記録された日は、通常営業日と比較して${names[difference.key]}が${difference.delta>=0?"高い":"低い"}傾向があります。`:""}
 return {GROUPS,TAGS,normalize,metrics,analyze,sentence};
});
