(function(root,factory){const api=factory();if(typeof module==="undefined"||!module.exports)root.DailyReview=api;else module.exports=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
"use strict";
const number=value=>Number.isFinite(Number(value))?Math.max(0,Number(value)):0,average=(rows,getter)=>rows.length?rows.reduce((sum,row)=>sum+number(getter(row)),0)/rows.length:0,ratio=(value,target)=>target>0?Math.max(0,Math.min(1.2,value/target)):1;
const rates=entry=>{const patients=number(entry?.patients),clinical=entry?.clinical||{},rate=value=>patients?number(value)/patients:0;return{unitPrice:patients?number(entry.sales)/patients:0,examRate:rate(number(clinical.bloodTests)+number(clinical.xrays)+number(clinical.ultrasounds)),newPatientRate:rate(entry?.newPatients),surgeryRate:rate(entry?.surgeries),checkupRate:rate(entry?.checkups),preventiveRate:rate(clinical.preventive)}};
function build(context={}){const entries=(Array.isArray(context.entries)?context.entries:[]).filter(entry=>number(entry?.patients)>0&&number(entry?.sales)>0).sort((a,b)=>String(a.date).localeCompare(String(b.date))),date=String(context.date||""),candidate=context.entry||entries.find(entry=>entry.date===date),today=candidate&&(number(candidate.patients)>0||number(candidate.sales)>0)?candidate:null,history=entries.filter(entry=>(!date||entry.date<date)).slice(-30);if(!today)return{ready:false,reason:"today-data"};if(history.length<3)return{ready:false,reason:"history"};
 const current=rates(today),baseline=Object.fromEntries(["unitPrice","examRate","newPatientRate","surgeryRate","checkupRate","preventiveRate"].map(key=>[key,average(history,row=>rates(row)[key])])),profitRate=Number.isFinite(Number(context.profitRate))?Number(context.profitRate):30;
 const metricScores=[ratio(current.unitPrice,baseline.unitPrice),ratio(profitRate,30),ratio(current.examRate,baseline.examRate),ratio(current.newPatientRate,baseline.newPatientRate),ratio(current.surgeryRate,baseline.surgeryRate),ratio(current.checkupRate,baseline.checkupRate),ratio(current.preventiveRate,baseline.preventiveRate),context.anomalies?.some(item=>item.level==="danger")?0.45:context.anomalies?.some(item=>item.level==="warning")?0.7:1,context.missionAchieved===false?0.6:1],score=Math.round(Math.max(0,Math.min(100,metricScores.reduce((sum,value)=>sum+value,0)/metricScores.length*89))),stars=Math.max(1,Math.min(5,Math.round(score/20)));
 const comparisons=[{label:"検査率",value:current.examRate,base:baseline.examRate,good:"検査提案が機能し、客単価向上に貢献しました。",action:"画像検査提案",effectLabel:"利益",effectValue:18000},{label:"新患率",value:current.newPatientRate,base:baseline.newPatientRate,good:"新患対応が平均を上回りました。",action:"新患フォロー",effectLabel:"客単価",effectValue:900},{label:"手術率",value:current.surgeryRate,base:baseline.surgeryRate,good:"手術対応が診療成果を押し上げました。",action:"手術候補の確認",effectLabel:"利益",effectValue:18000},{label:"健診率",value:current.checkupRate,base:baseline.checkupRate,good:"健診案内が継続診療につながりました。",action:"健診フォロー",effectLabel:"客単価",effectValue:900},{label:"客単価",value:current.unitPrice,base:baseline.unitPrice,good:"客単価が通常を上回りました。",action:"画像検査提案",effectLabel:"客単価",effectValue:900}].map(item=>({...item,change:item.base>0?item.value/item.base-1:0})),best=[...comparisons].sort((a,b)=>b.change-a.change)[0],weak=[...comparisons].sort((a,b)=>a.change-b.change)[0],improvement=weak.change<-.05?`${weak.label}が通常より低下しました。`:"大きな低下はありません。提案の再現性を高めましょう。",action=weak.change<-.05?weak:comparisons[0],comment=score>=85?`今日は十分良い診療でした。明日は${action.action}だけ意識しましょう。`:`今日は着実な診療でした。明日は${action.action}に集中しましょう。`;
 return{ready:true,score,stars,best:best.change>0?best.good:"日々の診療を安定して完了できました。",improvement,priority:action.action,effect:{label:action.effectLabel,value:action.effectValue},comment};}
return{build};
});
