"use strict";
(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.DailyShadowBrief=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
const EMPTY="先生、データが増えるほど影武者は賢くなります。今日は入力を積み重ねましょう。",WEEKDAYS=["日曜日","月曜日","火曜日","水曜日","木曜日","金曜日","土曜日"],safe=v=>Math.max(0,Number(v)||0),average=v=>v.length?v.reduce((s,x)=>s+x,0)/v.length:0;
const localDate=v=>{const [y,m,d]=String(v).split("-").map(Number);return new Date(y,m-1,d,12)},isoLocal=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,yen=v=>`${Math.round(safe(v)).toLocaleString("ja-JP")}円`,manYen=v=>safe(v)>=10000?`${Math.round(safe(v)/10000).toLocaleString("ja-JP")}万円`:yen(v),periodLead=h=>h<12?"今日は":h<18?"午前の実績を見ると":"本日の振り返りです。",item=(text,confidence,source)=>({text,confidence,source}),valid=e=>/^\d{4}-\d{2}-\d{2}$/.test(e?.date||"")&&(safe(e.sales)>0||safe(e.patients)>0);
function goal(c){const sales=safe(c.todayEntry.sales),target=safe(c.dailyTarget);if(!target)return null;if(sales>=target)return item(`${periodLead(c.hour)}本日の目標を達成しました。診療品質を優先しましょう。`,"high","goal");return item(`先生、${periodLead(c.hour)}あと${yen(target-sales)}で本日の目標達成です。`,"high","goal")}
function weekday(c){const day=localDate(c.today).getDay(),same=c.history.filter(e=>localDate(e.date).getDay()===day);if(same.length<4||c.history.length<12)return null;const unit=e=>safe(e.patients)?safe(e.sales)/safe(e.patients):0,wu=average(same.map(unit).filter(Boolean)),au=average(c.history.map(unit).filter(Boolean)),ws=average(same.map(e=>safe(e.sales))),as=average(c.history.map(e=>safe(e.sales)));if(au&&wu>=au*1.1)return item(`今日は${WEEKDAYS[day]}です。平均客単価が高い曜日です。`,"medium","weekday");if(as&&Math.abs(ws/as-1)<=.08)return item(`${WEEKDAYS[day]}は売上が安定しています。`,"medium","weekday");return null}
function yesterday(c){const date=localDate(c.today);date.setDate(date.getDate()-1);const old=c.entries.find(e=>e.date===isoLocal(date));if(!valid(old)||!valid(c.todayEntry))return null;const np=safe(c.todayEntry.patients),op=safe(old.patients),nu=np?safe(c.todayEntry.sales)/np:0,ou=op?safe(old.sales)/op:0;if(nu&&ou&&Math.abs(nu/ou-1)>=.05)return item(`昨日より客単価が${Math.round(Math.abs(nu/ou-1)*100)}%${nu>ou?"高く":"低く"}推移しています。`,"high","yesterday");if(np!==op)return item(`昨日より来院数が${np>op?"多い":"少ない"}状況です。`,"high","yesterday");return null}
function monthly(c){const target=safe(c.monthlyTarget);if(!target)return null;const sales=c.monthEntries.reduce((s,e)=>s+safe(e.sales),0),remaining=Math.max(0,target-sales);return remaining?item(`月目標まであと${manYen(remaining)}です。現在達成率${Math.round(sales/target*100)}%です。`,"high","monthly"):item("月目標を達成しています。現在の診療品質を維持しましょう。","high","monthly")}
function suggestion(c){const day=localDate(c.today).getDay(),same=c.history.filter(e=>localDate(e.date).getDay()===day),patients=safe(c.todayEntry.patients);if(same.length<3)return null;const expected=average(same.map(e=>safe(e.patients)).filter(Boolean));if(patients&&expected&&patients<expected*.8)return item("来院数が曜日平均未満です。当日対応の余力を確認しましょう。","medium","suggestion");return item("曜日実績を意識し、診療内容と客単価を確認しましょう。","medium","suggestion")}
const DEFAULT_SOURCES=[goal,weekday,yesterday,monthly,suggestion];
function generateDailyBrief(input={},options={}){const today=input.today||isoLocal(new Date()),entries=(input.entries||[]).filter(valid),todayEntry=entries.find(e=>e.date===today)||{},history=entries.filter(e=>e.date<today),month=today.slice(0,7);if(history.length<3)return {insights:[item(EMPTY,"high","empty")],empty:true};const c={...input,today,entries,todayEntry,history,monthEntries:entries.filter(e=>e.date.startsWith(month)),hour:Number.isFinite(Number(input.hour))?Number(input.hour):new Date().getHours()},seen=new Set(),insights=[];for(const source of options.sources||DEFAULT_SOURCES){const x=source(c);if(!x||x.confidence==="low"||Array.from(x.text).length>60)continue;const key=x.text.replace(/[\d,.、。％%円万]/g,"");if(seen.has(key))continue;seen.add(key);insights.push(x);if(insights.length===5)break}return {insights:insights.length>=3?insights:[item(EMPTY,"high","empty")],empty:insights.length<3}}
return {EMPTY,DEFAULT_SOURCES,generateDailyBrief,periodLead};});
