"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs");
const app=fs.readFileSync("app.js","utf8"),html=fs.readFileSync("index.html","utf8"),sw=fs.readFileSync("sw.js","utf8");
assert.match(html,/id="todayEntryMemo"[^>]*name="memo"/);
assert.match(app,/entry\?\.memo\?\?entry\?\.note\?\?""/,"legacy memo text loads into the unified modal");
assert.match(app,/existing=index>=0\?data\.entries\[index\]:\{\}/);
assert.match(app,/entry=\{\.\.\.existing,date,/,"existing fields are merged before saving");
assert.match(app,/entry.note=entry.memo/,"memo remains mirrored for legacy readers");
assert.match(app,/if\(index>=0\)data.entries\[index\]=entry/,"same-day saves update the existing entry");
assert.doesNotMatch(html,/id="note"|id="noteStatus"/);
assert.match(sw,/v9506-remove-legacy-entry-dom/);assert.match(html,/app\.js\?v=9506/);
console.log("unified modal memo edit/append safety tests passed");
