"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs");
const {EMPTY,buildDailyShadowIntelligence,buildDailyShadowActions,getClinicalAnalysisReadiness,generateDailyBrief,periodLead}=require("./daily-brief.js");
const build=(entries,extra={})=>buildDailyShadowIntelligence({today:"2026-08-02",entries,monthlyTarget:5000000,remainingBusinessDays:25,...extra});
assert.equal(periodLead(8),"今日は");assert.equal(periodLead(14),"午前の実績を見ると");assert.equal(periodLead(20),"本日の振り返りです。");
let result=build([], {monthlyTarget:0});assert.equal(result[0].message,EMPTY,"past data absent falls back");
result=build([{date:"2026-08-01",sales:100000,patients:10}],{monthlyTarget:0});assert.equal(result[0].type,"fallback","one day falls back");
result=build([{date:"2026-07-30",sales:100000,patients:10},{date:"2026-07-31",sales:130000,patients:10},{date:"2026-08-01",sales:180000,patients:12}]);assert.ok(result.some(x=>x.type==="previousDay"),"three days compare latest business days across month");
result=build([{date:"2026-07-30",sales:100000,patients:0},{date:"2026-08-01",sales:120000,patients:0}],{monthlyTarget:0});assert.ok(result.every(x=>x.metric!=="unitPrice"),"zero patients never calculates unit price");
result=build([{date:"2026-07-30",sales:100000,patients:10},{date:"2026-08-01",sales:0,patients:10}],{monthlyTarget:0});assert.ok(result.some(x=>x.metric==="patients")===false,"zero sales remains safe");
const sundays=["2026-06-14","2026-06-21","2026-06-28","2026-07-05","2026-07-12","2026-07-19","2026-07-26"].map(date=>({date,sales:240000,patients:20}));
const weekdays=["2026-07-07","2026-07-08","2026-07-09","2026-07-10","2026-07-14","2026-07-15"].map(date=>({date,sales:100000,patients:10}));
result=build([...sundays,...weekdays]);const trend=result.find(x=>x.type==="weekday");assert.ok(trend&&trend.sampleSize>=3,"3+ same weekdays yields trend and sample size");
result=build([], {today:"2026-08-01",remainingBusinessDays:20});const monthly=result.find(x=>x.type==="monthly");assert.equal(monthly.remainingBusinessDays,20,"month rollover calculation works without data");assert.ok(monthly.requiredDailySales>0);
result=build([], {today:"2026-08-03",monthlyTarget:0});assert.equal(result[0].type,"fallback","closed Monday safely falls back");
result=build([{date:"2026-07-29",sales:100000,patients:10},{date:"2026-07-31",sales:130000,patients:10}],{today:"2026-08-01",monthlyTarget:0,clinic:{closedDates:["2026-07-30"]}});assert.ok(result.some(x=>x.type==="previousDay"),"temporary closures use business-day history");
result=build([], {anomalies:[{level:"danger",metric:"客単価",changePercent:-24,sampleSize:4}]});assert.equal(result[0].type,"danger");assert.equal(result[0].priority,100,"danger has highest priority");
result=build([{date:"2026-07-30",sales:100000,patients:10},{date:"2026-08-01",sales:140000,patients:10}],{monthlyTarget:0});assert.ok(result.some(x=>x.level==="good"),"20% positive movement is Good anomaly");
assert.doesNotThrow(()=>generateDailyBrief({entries:null}),"old backup shape cannot crash");assert.equal(buildDailyShadowIntelligence({get entries(){throw Error("bad backup")}})[0].type,"fallback","builder contains failures");
assert.ok(result.length<=3,"maximum three comments");
const actions=(entries,extra={})=>buildDailyShadowActions({today:"2026-08-02",entries,monthlyTarget:5000000,remainingBusinessDays:25,...extra});
let briefing=actions([]);assert.deepEqual(briefing.map(x=>x.category),["review","action","goal"],"always returns the three action briefing blocks");assert.match(briefing[0].message,/蓄積中/,"no-data review has a useful fallback");
briefing=actions([{date:"2026-07-31",sales:100000,patients:10},{date:"2026-08-01",sales:140000,patients:10}]);assert.equal(briefing[0].level,"good","good movement is selected for review");assert.ok(briefing[0].evidence,"review exposes evidence");
briefing=actions([], {anomalies:[{level:"danger",metric:"客単価",current:9800,baseline:13000,changePercent:-24}]});assert.equal(briefing[0].level,"danger","danger overrides ordinary review");assert.match(briefing[1].message,/今後数日/,"danger creates a monitoring action without asserting a cause");
briefing=actions([], {today:"2026-08-03"});assert.match(briefing[1].message,/休診日/,"closed day receives a closed-day suggestion");
briefing=actions([{date:"2026-08-01",sales:5100000,patients:20}]);assert.match(briefing[2].message,/達成しています/,"achieved goal does not encourage more sales");assert.match(briefing[2].message,/診療負荷/,"achieved goal emphasizes sustainable operations");
const clinical=n=>{const rows=[];for(let i=0;rows.length<n;i++){const d=new Date(2026,0,1+i,12);if(d.getDay()===1)continue;rows.push({date:d.toLocaleDateString("sv-SE"),sales:100000,patients:10,clinical:{bloodTests:0,xrays:0,ultrasounds:0,revisits:0,preventive:0}})}return rows};assert.deepEqual(getClinicalAnalysisReadiness(clinical(7)),{sampleDays:7,ready:false,referenceOnly:false});assert.equal(getClinicalAnalysisReadiness(clinical(10)).referenceOnly,true,"10-29 clinical days are reference-only");assert.equal(getClinicalAnalysisReadiness(clinical(30)).ready,true,"30 clinical days are ready for future analysis");assert.equal(getClinicalAnalysisReadiness([{date:"2026-07-01",sales:1,patients:1}]).sampleDays,0,"old backup without clinical remains compatible");assert.equal(getClinicalAnalysisReadiness([{date:"2026-07-01",sales:1,patients:1,clinical:{bloodTests:1,xrays:2,ultrasounds:0,revisits:3,preventive:4,checkups:9,trimmings:8}}]).sampleDays,1,"old seven-key clinical object remains compatible");
assert.equal(buildDailyShadowActions({get entries(){throw Error("old malformed backup")}}).length,3,"action builder independently contains malformed backup failures");
assert.match(fs.readFileSync("style.css","utf8"),/@media\(prefers-reduced-motion:reduce\)\{\.daily-shadow-insights li\{animation:none!important\}\}/,"reduced motion retained");
const app=fs.readFileSync("app.js","utf8");assert.match(app,/function renderDailyShadowBrief\(\)[\s\S]*?catch\(error\)\{console\.error\(error\);showEmpty\(\)\}/,"render is independently guarded");
const started=performance.now();for(let i=0;i<100;i++)build([...sundays,...weekdays]);assert.ok((performance.now()-started)/100<20,"under 20ms");
console.log("Daily Shadow Intelligence: 16 scenarios passed");
