const test=require("node:test"),assert=require("node:assert/strict"),rates=require("./examination-rates"),HolidayAnalysis=require("./holiday-analysis");

test("患者88件の検査実施率を総数から計算する",()=>{const result=rates.calculateExaminationRates({patients:88,bloodTests:12,imaging:2});assert.equal(result.bloodRate.toFixed(1),"13.6");assert.equal(result.imagingRate.toFixed(1),"2.3")});
test("患者0件は計算対象外になりNaNやInfinityを返さない",()=>{const result=rates.calculateExaminationRates({patients:0,bloodTests:12,imaging:2});assert.equal(result.bloodRate,null);assert.equal(result.imagingRate,null)});
test("通常より20%以上低い画像検査率だけを検出する",()=>{const result=rates.compareExaminationRates({bloodRate:16,imagingRate:2.3},{bloodRate:18,imagingRate:7.5});assert.equal(result.bloodLow,false);assert.equal(result.imagingLow,true);assert.ok(result.imagingDecline>69)});

const clinical=(bloodTests,xrays,ultrasounds=0)=>({bloodTests,xrays,ultrasounds});
test("患者数が通常水準で客単価と画像検査率が低い場合は診療単価低下型にする",()=>{const entries=[];for(let i=1;i<=5;i++)entries.push({date:`2026-06-0${i}`,sales:1000,patients:10,clinical:clinical(2,1)});entries.push({date:"2026-08-10",sales:800,patients:10,clinical:clinical(2,0)});const result=HolidayAnalysis.analyze(entries,{start:"2026-08-10",end:"2026-08-10",comparisonDays:100});assert.ok(Math.abs(result.changes.unitPrice+20)<1e-9);assert.equal(result.examination.compositionEffect,true);assert.equal(result.type,"診療単価低下型")});
test("検査率低下がなければ診療内容補足条件を満たさない",()=>{const entries=[];for(let i=1;i<=5;i++)entries.push({date:`2026-06-0${i}`,sales:1000,patients:10,clinical:clinical(2,1)});entries.push({date:"2026-08-10",sales:800,patients:10,clinical:clinical(2,1)});const result=HolidayAnalysis.analyze(entries,{start:"2026-08-10",end:"2026-08-10",comparisonDays:100});assert.equal(result.examination.comparison.bloodLow,false);assert.equal(result.examination.comparison.imagingLow,false);assert.equal(result.examination.compositionEffect,false)});
test("直前3か月のデータが5日未満なら比較データ不足",()=>{const result=HolidayAnalysis.analyze([{date:"2026-08-01",sales:1000,patients:10,clinical:clinical(2,1)},{date:"2026-08-10",sales:800,patients:10,clinical:clinical(1,0)}],{start:"2026-08-10",end:"2026-08-10"});assert.equal(result.examination.dataSufficient,false);assert.equal(result.examination.normal.bloodRate,null)});
