(function(root,factory){
 const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.KnowledgeCore=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(){
 "use strict";
 const MAX_ITEMS=100,VALID_TRENDS=new Set(["up","down","stable","new"]),trendScore={up:3,new:2,stable:1,down:0};
 const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||"")),clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0)),idOf=value=>String(value?.id||value?.key||value?.theme||"").trim(),number=value=>Number(value)||0;
 function normalize(library){return (Array.isArray(library)?library:[]).filter(item=>item&&idOf(item)&&typeof item.theme==="string").map(item=>{const firstSeen=validDate(item.firstSeen)?item.firstSeen:(validDate(item.lastSeen)?item.lastSeen:"1970-01-01"),lastSeen=validDate(item.lastSeen)?item.lastSeen:firstSeen,confidence=clamp(item.confidence||1,1,5),count=Math.max(1,Math.trunc(Number(item.count??item.sampleCount)||1));return {...item,id:idOf(item),theme:String(item.theme),confidence,score:clamp(item.score??confidence*20,0,100),importance:clamp(item.importance||confidence||1,1,100),count,sampleCount:count,firstSeen,lastSeen,lastUpdated:item.lastUpdated||lastSeen,metrics:item.metrics&&typeof item.metrics==="object"&&!Array.isArray(item.metrics)?{...item.metrics}:{},trend:VALID_TRENDS.has(item.trend)?item.trend:"stable",season:String(item.season||"通年"),weekday:String(item.weekday||"全曜日"),comment:String(item.comment||""),category:String(item.category||"general")}}).sort((a,b)=>b.score-a.score||b.confidence-a.confidence||b.importance-a.importance||trendScore[b.trend]-trendScore[a.trend]||b.count-a.count||b.lastSeen.localeCompare(a.lastSeen)||a.id.localeCompare(b.id)).slice(0,MAX_ITEMS)}
 function find(library,query){const value=typeof query==="object"?idOf(query):String(query||"");return normalize(library).find(item=>item.id===value||item.theme===value)||null}
 function rank(library,{limit=MAX_ITEMS,category}={}){return normalize(library).filter(item=>!category||item.category===category).slice(0,Math.max(0,limit))}
 function getTopThemes(library,options={}){return rank(library,{...options,limit:options.limit||1})}
 function merge(library,candidate,{weekly=false}={}){const current=normalize(library),id=idOf(candidate);if(!id)return current;const index=current.findIndex(item=>item.id===id);if(index<0)return normalize([...current,{...candidate,id,firstSeen:candidate.firstSeen||candidate.lastSeen,count:candidate.count||1,trend:candidate.trend||"new"}]);const old=current[index],next=weekly?{...old,count:Math.max(old.count,Number(candidate.count)||old.count+1),sampleCount:Math.max(old.count,Number(candidate.count)||old.count+1),trend:candidate.trend||old.trend,lastSeen:candidate.lastSeen||old.lastSeen,lastUpdated:candidate.lastSeen||old.lastSeen}:{...old,...candidate,id,firstSeen:old.firstSeen,count:Number(candidate.count)||old.count};current[index]=next;return normalize(current)}
 function update(library,candidates,options={}){return (Array.isArray(candidates)?candidates:[candidates]).filter(Boolean).reduce((items,item)=>merge(items,item,options),normalize(library))}
 function learn(library,candidate){return merge(library,{...candidate,category:candidate?.category||"learning",trend:candidate?.trend||"new"})}
 const has=(object,key)=>object!=null&&Object.prototype.hasOwnProperty.call(object,key)&&object[key]!==""&&Number.isFinite(Number(object[key]));
 function metricValue(entry,keys){for(const key of keys){if(has(entry,key))return Number(entry[key]);if(has(entry?.clinical,key))return Number(entry.clinical[key])}return null}
 function analyzeScorePatterns(entries,scoreHistory,{today="9999-12-31"}={}){
  const scores=new Map((Array.isArray(scoreHistory)?scoreHistory:[]).filter(x=>x&&validDate(x.date)&&Number.isFinite(Number(x.score))).map(x=>[x.date,Number(x.score)])),rows=(Array.isArray(entries)?entries:[]).filter(e=>e&&validDate(e.date)&&e.date<=today&&scores.has(e.date)).map(entry=>({entry,score:scores.get(entry.date)})).sort((a,b)=>a.score-b.score||a.entry.date.localeCompare(b.entry.date)),sampleDays=rows.length,reliability=sampleDays<10?"参考値":sampleDays<30?"傾向あり":"比較的安定";
  if(sampleDays<3)return {ready:false,sampleDays,reliability,successPatterns:[],attentionPatterns:[],strategies:[]};
  const size=Math.max(1,Math.floor(sampleDays/3)),low=rows.slice(0,size),high=rows.slice(-size),normal=rows.slice(size,-size);
  if(!normal.length)return {ready:false,sampleDays,reliability,successPatterns:[],attentionPatterns:[],strategies:[]};
  const count=(label,keys,priority=false)=>({label,value:e=>metricValue(e,keys),priority}),rateMetric=(label,keys,priority=false)=>({label,value:e=>{const patients=metricValue(e,["patients"]),part=metricValue(e,keys);return patients!==null&&patients>0&&part!==null?part/patients*100:null},priority});
  const derivedRate=(label,numerator,priority=false)=>({label,priority,value:e=>{const patients=metricValue(e,["patients"]),part=numerator(e);return patients!==null&&patients>0&&part!==null?part/patients*100:null}}),combined=(entry,keys)=>{const values=keys.map(key=>metricValue(entry,[key])).filter(value=>value!==null);return values.length?values.reduce((sum,value)=>sum+value,0):null};
  const metrics=[count("売上",["sales"]),count("患者数",["patients"]),{label:"客単価",value:e=>{const patients=metricValue(e,["patients"]),sales=metricValue(e,["sales"]);return patients!==null&&patients>0&&sales!==null?sales/patients:null}},count("新患数",["newPatients"]),rateMetric("新患率",["newPatients"]),derivedRate("再診率",e=>{const explicit=metricValue(e,["repeatPatients","revisits"]),patients=metricValue(e,["patients"]),newPatients=metricValue(e,["newPatients"]);return explicit!==null?explicit:patients!==null&&newPatients!==null?Math.max(0,patients-newPatients):null}),rateMetric("予防率",["preventive","vaccines"],true),rateMetric("血液検査率",["bloodTests"],true),derivedRate("画像検査率",e=>metricValue(e,["imaging"])??combined(e,["xrays","xray","ultrasounds","ultrasound"]),true),count("手術件数",["surgeries"]),count("トリミング件数",["trimmings","trimming"]),count("利益率",["profitRate"] )];
  const avg=(group,metric)=>{const values=group.map(row=>metric.value(row.entry)).filter(value=>value!==null);return values.length?{value:values.reduce((sum,value)=>sum+value,0)/values.length,count:values.length}:null},compare=(group,type)=>metrics.map(metric=>{const target=avg(group,metric),base=avg(normal,metric);if(!target||!base||base.value===0)return null;const difference=(target.value-base.value)/Math.abs(base.value)*100;if(type==="success"?difference<=0:difference>=0)return null;return {metric:metric.label,difference,absDifference:Math.abs(difference),targetAverage:target.value,normalAverage:base.value,sampleCount:Math.min(target.count,base.count),priority:metric.priority,text:`${type==="success"?"高":"低"}スコア日に${metric.label}が通常営業日より${Math.round(Math.abs(difference))}%${type==="success"?"高い":"低い"}傾向があります（${reliability}・${sampleDays}営業日、関連傾向であり因果を示しません）。`}}).filter(Boolean).sort((a,b)=>Number(b.priority)-Number(a.priority)||b.absDifference-a.absDifference||a.metric.localeCompare(b.metric)).slice(0,3);
  const successPatterns=compare(high,"success"),attentionPatterns=compare(low,"attention"),actions={"予防率":"必要な患者への予防案内が、適切な時期に行えているか確認する","血液検査率":"血液検査が必要な症例で、適応と説明に漏れがないか確認する","画像検査率":"画像検査が必要な症例で、適応と提案に漏れがないか確認する","再診率":"継続診療が必要な症例の再診予定と案内を確認する","新患率":"新患の診療後に必要な再診や予防案内ができているか確認する","客単価":"診療内容を振り返り、必要な検査・処置の説明に漏れがないか確認する","利益率":"診療品質を維持しながら、支出内訳と業務の無理を確認する"},strategies=[];
  for(const item of [...attentionPatterns,...successPatterns]){const action=actions[item.metric];if(action&&!strategies.some(x=>x.metric===item.metric)){strategies.push({metric:item.metric,action,source:attentionPatterns.includes(item)?"attention":"success"});if(strategies.length===2)break}}
  return {ready:true,sampleDays,reliability,groups:{high:high.length,normal:normal.length,low:low.length},successPatterns,attentionPatterns,strategies};
 }
 function clinical(entry,key){const c=entry?.clinical||{};const aliases={imaging:["imaging","xrays","ultrasounds"],checkup:["checkups"],surgery:["surgeries"],prevention:["preventive"]};return (aliases[key]||[key]).reduce((sum,name)=>sum+number(entry?.[name]??c[name]),0)}
 function period(entries,month){const rows=(Array.isArray(entries)?entries:[]).filter(e=>String(e.date||"").startsWith(month));return {rows,sales:rows.reduce((s,e)=>s+number(e.sales),0),patients:rows.reduce((s,e)=>s+number(e.patients),0),checkup:rows.reduce((s,e)=>s+clinical(e,"checkup"),0),surgery:rows.reduce((s,e)=>s+clinical(e,"surgery"),0),imaging:rows.reduce((s,e)=>s+clinical(e,"imaging"),0),prevention:rows.reduce((s,e)=>s+clinical(e,"prevention"),0)}}
 const shiftMonth=(month,delta)=>{const [y,m]=month.split("-").map(Number),d=new Date(Date.UTC(y,m-1+delta,1));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`};
 function buildStrategyDashboard({entries=[],successLibrary=[],scoreHistory=[],today=new Date().toISOString().slice(0,10),target=0,expense=0,businessDays=0,successPatterns=[],clinicalSnapshot=null}={}){
  const library=rank(successLibrary),month=today.slice(0,7),current=period(entries,month),previous=period(entries,shiftMonth(month,-1)),lastYear=period(entries,`${Number(month.slice(0,4))-1}${month.slice(4)}`),top=library[0];
  const weighted=item=>Math.round(clamp((number(item.metrics?.profit)*.4)+(number(item.metrics?.unit)*.2)+(number(item.metrics?.revisitRate)*.15)+(number(item.metrics?.visits)*.15)+(number(item.metrics?.continuationRate)*.1)+(item.score||0),0,100));
  const successRanking=library.map(item=>({...item,rankingScore:weighted(item),profitImprovement:number(item.metrics?.profit)})).sort((a,b)=>b.rankingScore-a.rankingScore).slice(0,5);
  const names={checkup:"健診",surgery:"手術",imaging:"画像検査",prevention:"予防"};
  const growth=Object.keys(names).map(key=>{const base=previous[key],yearBase=lastYear[key],mom=base?Math.round((current[key]-base)/base*100):0,yoy=yearBase?Math.round((current[key]-yearBase)/yearBase*100):0;return {theme:names[key],value:current[key],mom,yoy}}).sort((a,b)=>b.mom-a.mom).slice(0,5);
  const unit=current.patients?current.sales/current.patients:0,previousUnit=previous.patients?previous.sales/previous.patients:0,profit=current.sales-expense,profitRate=current.sales?profit/current.sales*100:0;
  const warnings=[{theme:"客単価",change:previousUnit?Math.round((unit-previousUnit)/previousUnit*100):0},{theme:"再診率",change:0},{theme:"健診率",change:previous.patients?Math.round((current.checkup/Math.max(1,current.patients)-previous.checkup/previous.patients)*100):0},{theme:"画像検査率",change:previous.patients?Math.round((current.imaging/Math.max(1,current.patients)-previous.imaging/previous.patients)*100):0},{theme:"利益率",change:Math.round(profitRate-30)}].filter(x=>x.change<0).map(x=>({...x,priority:clamp(Math.ceil(Math.abs(x.change)/5),1,5)})).sort((a,b)=>b.priority-a.priority);
  const elapsed=current.rows.filter(e=>e.date<=today).length,remaining=Math.max(0,number(businessDays)-elapsed),dailySales=elapsed?current.sales/elapsed:0,forecastSales=Math.round(current.sales+dailySales*remaining),forecastProfit=Math.round(forecastSales-(expense||0)),forecastRate=forecastSales?forecastProfit/forecastSales*100:0;
  const expectedSales=top?Math.max(0,Math.round(number(top.metrics?.unit)*Math.max(1,top.confidence)/100)*100):0,expectedProfit=Math.round(expectedSales*Math.max(0,profitRate)/100);
  const safeAction=top?`${top.theme}は適応・必要性を確認し、見逃し防止と継続診療を意識してください。`:"予約と継続診療の必要性を確認してください。";
  const brief={priority:top?.theme||"継続診療",risk:warnings[0]?.theme||"大きな低下なし",expectedProfit,expectedSales,clinical:top?.theme||"予約症例",comment:safeAction};
  const active=clinicalSnapshot?[clinicalSnapshot.imaging>0&&"画像検査",clinicalSnapshot.healthChecks>0&&"健診",clinicalSnapshot.bloodTests>0&&"血液検査",clinicalSnapshot.newPatients>0&&"新患"].filter(Boolean):[],matches=(Array.isArray(successPatterns)?successPatterns:[]).map(item=>{const features=Array.isArray(item.features)?item.features:[];return features.length?features.filter(x=>active.includes(x)).length/features.length*100:0}),successPatternMatch=Math.round(Math.max(...matches,0));
  const tomorrow={theme:library[1]?.theme||top?.theme||"継続診療",expectedProfit:Math.round(expectedProfit*.7),successPatternMatch,comment:`明日は${library[1]?.theme||top?.theme||"予約症例"}について適応と必要性を確認します。成功日パターン一致率は${successPatternMatch}％です。`};
  const discoveries=library.slice(0,3).map(item=>`${item.weekday!=="全曜日"?item.weekday+"は":""}${item.theme}で${item.comment||"良い指標がみられる傾向"}`).map(text=>`${text.replace(/。+$/,"")}（関連傾向であり、因果を示しません）。`);
  const seasonLearning=library.filter(item=>item.season!=="通年").slice(0,5).map(item=>({season:item.season,theme:item.theme,trend:item.trend,confidence:item.confidence}));
  const strategyMap={strength:successRanking.slice(0,3).map(x=>x.theme),improvement:warnings.slice(0,3).map(x=>x.theme),growth:growth.filter(x=>x.mom>0).slice(0,3).map(x=>x.theme)};
  const coach={date:today,checkups:current.rows.find(e=>e.date===today)?.checkups||0,imaging:clinical(current.rows.find(e=>e.date===today)||{},"imaging"),unitChange:previousUnit?Math.round((unit-previousUnit)/previousUnit*100):0,comment:`今日は${brief.priority}について、適応と必要性を確認した診療を振り返りましょう。`};
  const scorePatterns=analyzeScorePatterns(entries,scoreHistory,{today});
  return {brief,successRanking,growth,warnings,discoveries,tomorrow,seasonLearning,scorePatterns,forecast:{sales:forecastSales,profit:forecastProfit,profitRate:forecastRate,achievement:target?forecastSales/target*100:0,remainingBusinessDays:remaining,model:"Knowledge Core"},coach,strategyMap};
 }
 return {MAX_ITEMS,normalize,getTopThemes,update,rank,find,learn,merge,analyzeScorePatterns,buildStrategyDashboard};
});
