const test=require("node:test"),assert=require("node:assert/strict"),Insights=require("./learning-insights.js");
const Backup=require("./backup-normalizer.js");
const date=index=>new Date(Date.UTC(2026,5,index+1)).toISOString().slice(0,10);
function entries(count=20){return Array.from({length:count},(_,index)=>({date:date(index),patients:10,newPatients:0,sales:index%2?100000:200000,clinical:{xrays:index%2,ultrasounds:0,bloodTests:0,preventive:0}}))}
const correlatedEntries=({signal="newPatient",count=20}={})=>Array.from({length:count},(_,index)=>{const active=index%2===1,row={date:date(index),patients:active?13:10,newPatients:0,sales:(active?13:10)*10000,surgeries:0,checkups:0,clinical:{xrays:0,ultrasounds:0,bloodTests:0,preventive:0}};if(signal==="newPatient")row.newPatients=active?2:0;if(signal==="surgery")row.surgeries=active?1:0;if(signal==="imaging")row.clinical.xrays=active?1:0;return row});
const CAUSAL=/売上が上がる|利益が増える|来院増加につながる|客単価を上げる|利益改善に寄与する|だから/;
test("相関を観察と安全なヒントに分離し、因果表現を生成しない",()=>{const result=Insights.analyze(entries(),{today:"2026-07-01"});assert.equal(result.ready,true);assert.match(result.text,/^最近わかったこと\n\n/);assert.match(result.text,/\n\n今日へのヒント\n\n/);assert.match(result.result,/平均より.*傾向でした/);assert.match(result.hint,/適応/);assert.doesNotMatch(result.text,CAUSAL)});
test("新患の観察とヒントを分離する",()=>{const result=Insights.analyze(correlatedEntries(),{today:"2026-07-01"});assert.equal(result.key,"newPatient:visits");assert.match(result.result,/新患があった日は来院件数が平均より\d+%高い傾向でした/);assert.match(result.hint,/必要な再診や予防案内に漏れがないか確認/);assert.doesNotMatch(result.result,/案内|確認しましょう/)});
test("手術を増やす提案をせず、臨床適応を前提にする",()=>{const result=Insights.analyze(correlatedEntries({signal:"surgery"}),{today:"2026-07-01"});assert.match(result.result,/手術を実施した日/);assert.match(result.hint,/外科適応.*術前検査の必要性.*確認/);assert.doesNotMatch(result.text,/手術を増や|利益のため/)});
test("画像検査は売上目的でなく適応の見逃しを確認する",()=>{const result=Insights.analyze(correlatedEntries({signal:"imaging"}),{today:"2026-07-01"});assert.match(result.result,/画像検査を実施した日/);assert.match(result.hint,/適応がある症例を見逃していないか確認/);assert.doesNotMatch(result.text,/売上のため|積極的に増や/)});
test("データ不足",()=>assert.equal(Insights.analyze(entries(5),{today:"2026-07-01"}).text,Insights.EMPTY));
test("差が小さい場合は無理に学びを生成しない",()=>{const rows=correlatedEntries().map(row=>({...row,patients:10,sales:100000}));assert.deepEqual(Insights.analyze(rows,{today:"2026-07-01"}).text,"現在も診療データを学習中です。\n明確な傾向が確認できると表示します。")});
test("夜間保存と30件上限",()=>{const old=Array.from({length:30},(_,i)=>({date:`2026-05-${String(i+1).padStart(2,"0")}`,key:`old:${i}`,result:"結果",text:"結果"}));assert.equal(Insights.learnAtNight({entries:entries(),history:old,today:"2026-06-30",hour:17}).saved,false);const night=Insights.learnAtNight({entries:entries(),history:old,today:"2026-06-30",hour:18});assert.equal(night.saved,true);assert.equal(night.history.length,30)});
test("7日重複禁止",()=>{const first=Insights.analyze(entries(),{today:"2026-07-01"}),second=Insights.analyze(entries(),{today:"2026-07-01",history:[{date:"2026-06-30",key:first.key,result:first.result,text:first.text}]});assert.notEqual(second.key,first.key)});
test("翌朝に前夜の学習を表示",()=>{const night=Insights.learnAtNight({entries:entries(),history:[],today:"2026-06-30",hour:20});assert.equal(Insights.displayed({entries:entries(),history:night.history,today:"2026-07-01"}).date,"2026-06-30")});

test("JSONバックアップで履歴を維持し旧形式も復元する",()=>{const record={date:"2026-06-30",key:"imaging:unit",result:"結果",text:"結果"},defaults={entries:[],learningHistory:[],finance:{},clinic:{closedDates:[]},historical:{},settings:{},monthlyReports:{},memo:""};assert.deepEqual(Backup.normalizeBackup({entries:[],learningHistory:[record]},defaults,"key").data.learningHistory,[record]);assert.deepEqual(Backup.normalizeBackup({entries:[]},defaults,"key").data.learningHistory,[])});
