const assert=require("node:assert/strict"),Forecast=require("./monthly-profit-forecast.js");
const history=Array.from({length:6},()=>({sales:5000,expense:3500}));
const calculate=(days,extra={})=>Forecast.calculate({businessDays:days,scheduledBusinessDays:25,currentSales:days*200,currentExpense:2000,currentProfit:days*200-2000,fixedExpense:1500,variableExpense:500,historicalMonths:history,targetProfit:1500,...extra});
assert.deepEqual(Forecast.weights(5),{past:.9,current:.1,model:"過去6か月補正"},"5日以内は過去6か月を優先");
assert.equal(Forecast.weights(6).past,.7,"6〜10日は過去実績70%");
assert.equal(Forecast.weights(11).current,.6,"11〜20日は今月実績60%");
assert.equal(Forecast.weights(21).current,.9,"21日以降は今月実績90%");
assert.equal(calculate(5).projectedExpense,4000,"固定費は据え置き、変動費だけを外挿");
assert.equal(calculate(5).confidence.stars,"★★★★☆","十分な過去実績がある月初は高信頼");
assert.match(calculate(5).comment,/固定費計上の影響/,"月初向け影武者コメント");
assert.match(calculate(10).comment,/現在利益は参考値/,"10日以内向け影武者コメント");
assert.match(calculate(20).comment,/今月実績を主体/,"20日以降向け影武者コメント");
assert.equal(calculate(11,{previousForecast:1000}).difference,calculate(11).forecastProfit-1000,"前回予測との差を返す");
console.log("monthly profit forecast tests passed");
