const test=require("node:test"),assert=require("node:assert/strict"),Strategy=require("./today-winning-strategy");
const entries=(count,{boostStart=0,boost=40000,key="bloodTests"}={})=>Array.from({length:count},(_,i)=>{const active=i>=boostStart&&i%2===0;return{date:`2026-${String(1+Math.floor(i/28)).padStart(2,"0")}-${String(i%28+1).padStart(2,"0")}`,patients:10,newPatients:active?1:3,sales:100000+(active?boost:0),expense:60000,checkups:key==="checkups"&&active?1:0,clinical:{[key]:active?2:0}}});
test("学習データ0件と15営業日未満は学習中",()=>{for(const rows of [[],entries(14)]){const result=Strategy.build({entries:rows});assert.equal(result.ready,false);assert.equal(result.status,"学習中")}assert.equal(Strategy.MIN_BUSINESS_DAYS,15)});
test("直近30営業日を優先して実績から順位を更新",()=>{const result=Strategy.build({entries:entries(30)});assert.equal(result.ready,true);assert.equal(result.learningWindow,"直近30営業日");assert.equal(result.theme,"血液検査");assert.ok(result.expectedSales>0);assert.ok(result.expectedProfit>0);assert.equal(result.weights.expectedProfit,.45)});
test("30日でサンプル不足なら90営業日へフォールバック",()=>{const rows=entries(90);rows.slice(-30).forEach(row=>row.clinical.bloodTests=0);const learned=Strategy.learnCandidate(rows,Strategy.DEFINITIONS.find(item=>item.key==="blood"));assert.equal(learned.window,"直近90営業日")});
test("90日でも不足なら全期間へフォールバック",()=>{const rows=entries(120);rows.forEach((row,i)=>row.clinical.bloodTests=i<4?2:0);const learned=Strategy.learnCandidate(rows,Strategy.DEFINITIONS.find(item=>item.key==="blood"));assert.equal(learned.window,"全期間")});
test("夜の成功率差分で翌日の順位を更新",()=>{const rows=entries(30),before=Strategy.build({entries:rows}),after=Strategy.build({entries:rows,learningHistory:[{key:"blood",successRateDelta:-20}]});assert.ok(after.successRate<before.successRate)});
test("Missionは勝ち筋から最大3件を自動生成",()=>{const result=Strategy.build({entries:entries(30)});assert.equal(result.missions[0].title,result.title);assert.deepEqual(result.missions[0].actions,["対象症例を確認","血液検査を提案","結果説明と再診予定を確認"])});
test("利益率推定の互換APIを維持",()=>{const month=rate=>({sales:100,expense:100-rate});assert.equal(Strategy.stableProfitRate({recentMonths:[month(20),month(30),month(40)]}).source,"直近3か月")});
