(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.TodayMission=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
"use strict";
const n=value=>Number.isFinite(Number(value))?Number(value):0,avg=(rows,getter)=>rows.length?rows.reduce((sum,row)=>sum+n(getter(row)),0)/rows.length:0,rate=(total,patients)=>patients>0?total/patients*100:0;
const ACTIONS={unit:{title:"客単価改善",actions:["血液検査の適応を確認","超音波検査を提案"],effects:["利益率","客単価"]},profit:{title:"利益率改善",actions:["高原価の診療を確認","薬品の使用量を確認"],effects:["利益率","キャッシュフロー"]},patients:{title:"来院機会を増やす",actions:["当日空き枠を案内","再診予定へ連絡"],effects:["来院件数","新患"]},newPatient:{title:"新患導線を整える",actions:["口コミ返信を1件行う","症例情報を発信"],effects:["新患"]},revisit:{title:"再診フォロー",actions:["次回来院日を案内","未予約症例を確認"],effects:["再診率","来院件数"]},imaging:{title:"画像検査提案",actions:["超音波検査の適応を確認","画像検査枠を確保"],effects:["診断精度","客単価"]},blood:{title:"血液検査提案",actions:["健診時に検査を案内","術前検査を確認"],effects:["診断精度","利益率"]},surgery:{title:"手術候補の確認",actions:["手術適応症例を共有","術前検査を案内"],effects:["手術率","客単価"]},preventive:{title:"予防案内の徹底",actions:["予防対象をリスト化","会計時に次回を案内"],effects:["予防実施率","再診率"]},inventory:{title:"薬品補充を最適化",actions:["在庫数を確認","発注量を調整"],effects:["薬品補充率","キャッシュフロー"]}};
function add(list,key,score,reason,source){if(ACTIONS[key]&&score>0)list.push({key,...ACTIONS[key],score,reason,source})}function unique(items){const result=[],keys=new Set();for(const item of items.sort((a,b)=>b.score-a.score||a.key.localeCompare(b.key))){if(keys.has(item.key))continue;keys.add(item.key);result.push(item);if(result.length===3)break}return result}
function build(context={}){const entries=(Array.isArray(context.entries)?context.entries:[]).filter(row=>n(row?.patients)>0).sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(entries.length<3)return{ready:false,sampleDays:entries.length,missions:[],comment:null};const recent=entries.slice(-30),previous=entries.slice(-60,-30),t=recent.reduce((out,row)=>{const c=row.clinical||{};out.sales+=n(row.sales);out.patients+=n(row.patients);out.newPatients+=n(row.newPatients);out.surgeries+=n(row.surgeries);out.blood+=n(c.bloodTests);out.image+=n(c.xrays)+n(c.ultrasounds);out.preventive+=n(c.preventive);return out},{sales:0,patients:0,newPatients:0,surgeries:0,blood:0,image:0,preventive:0}),unit=t.patients?t.sales/t.patients:0,oldUnit=avg(previous,row=>n(row.patients)?n(row.sales)/n(row.patients):0),profitRate=t.sales?(t.sales-n(context.monthExpense))/t.sales*100:0,c=[];
if(oldUnit&&unit<oldUnit*.95)add(c,"unit",90+(1-unit/oldUnit)*40,`客単価が前期間より${Math.round((1-unit/oldUnit)*100)}%低い`,"Business Insight");if(context.monthExpense>0&&profitRate<20)add(c,"profit",95+(20-profitRate),`利益率が${profitRate.toFixed(1)}%`,"利益予測");const patients=avg(recent,row=>row.patients),oldPatients=avg(previous,row=>row.patients);if(oldPatients&&patients<oldPatients*.9)add(c,"patients",82,"来院件数が前期間を下回る","異常検知");const newRate=rate(t.newPatients,t.patients),revisitRate=100-newRate;if(newRate<10)add(c,"newPatient",72+(10-newRate),`新患率が${newRate.toFixed(1)}%`,"月間レポート");if(revisitRate<75)add(c,"revisit",70+(75-revisitRate),`再診率が${revisitRate.toFixed(1)}%`,"Clinical Intelligence");for(const [key,value,limit,score,label] of [["imaging",rate(t.image,t.patients),18,80,"画像検査率"],["blood",rate(t.blood,t.patients),20,76,"血液検査率"],["surgery",rate(t.surgeries,t.patients),5,62,"手術率"],["preventive",rate(t.preventive,t.patients),15,65,"予防実施率"]])if(value<limit)add(c,key,score+limit-value,`${label}が${value.toFixed(1)}%`,"Clinical Intelligence");for(const anomaly of context.anomalies||[]){const key=anomaly.metric==="客単価"?"unit":anomaly.metric==="来院件数"?"patients":anomaly.metric==="利益率"||anomaly.metric==="総支出"?"profit":null;if(key)add(c,key,110,`${anomaly.metric}に異常を検知`,"異常検知")}if(n(context.cashFlowLevel)>0&&n(context.cashFlowLevel)<=2)add(c,"inventory",92,"キャッシュフロー安全度が低い","キャッシュフロー予測");if(context.profitForecastRate!==undefined&&n(context.profitForecastRate)<80)add(c,"profit",98,"利益予測が目標を下回る","利益予測");let missions=unique(c);if(!missions.length){add(c,"revisit",50,"主要指標は安定。案内漏れを防ぐ","今日の影武者");missions=unique(c)}const top=missions[0];return{ready:true,sampleDays:entries.length,missions,comment:top?{quote:top.title,reason:top.reason,effect:top.effects[0]}:null}}
return{build};
});
