const test=require("node:test"),assert=require("node:assert/strict"),Weekly=require("./weekly-insights.js"),Backup=require("./backup-normalizer.js");
const date=index=>new Date(Date.UTC(2026,0,index+1)).toISOString().slice(0,10);
function entries(count=30,{recentMultiplier=1.2}={}){return Array.from({length:count},(_,index)=>{const active=index%2===0,recent=index>=count-7,patients=active&&recent?12:10;return {date:date(index),patients,newPatients:active?2:0,sales:patients*10000*(active&&recent?recentMultiplier:1),checkups:active?1:0,surgeries:0,clinical:{xrays:active?1:0,ultrasounds:0,bloodTests:0,preventive:0}}})}
const options={today:"2026-02-15"};

test("直近7営業日を解析し直近30営業日内の以前の営業日と比較する",()=>{const result=Weekly.analyze(entries(),options);assert.equal(result.recentDays,7);assert.equal(result.baselineDays,30);assert.equal(result.ready,true);assert.ok(result.insights.length<=3);assert.match(result.insights[0].text,/今週は、.*通常より\d+%.*傾向でした。/)});
test("重要度順で最大3件を返す",()=>{const result=Weekly.analyze(entries(),options);assert.ok(result.insights.length<=3);assert.deepEqual(result.insights.map(item=>item.importance),[...result.insights].sort((a,b)=>b.importance-a.importance).map(item=>item.importance))});
test("今日の学習とAI経営コンパスにあるキーは重複表示しない",()=>{const first=Weekly.analyze(entries(),options),keys=first.insights.map(item=>item.key),result=Weekly.analyze(entries(),{...options,learningHistory:[{date:"2026-02-14",key:keys[0]}],compassLearning:[{date:"2026-02-14",key:keys[1].split(":")[0]}]});assert.doesNotMatch(result.insights.map(item=>item.key).join(","),new RegExp(keys.slice(0,2).join("|")))});
test("生成文に因果表現を含めない",()=>{const text=Weekly.analyze(entries(),options).text;assert.doesNotMatch(text,/すると利益が上が|すれば売上が増|につなが|寄与|だから/);assert.match(text,/傾向でした/)});
test("4営業日未満、比較不能、差5%未満、サンプル不足では表示しない",()=>{assert.equal(Weekly.analyze(entries(3),options).text,Weekly.EMPTY);assert.equal(Weekly.analyze(entries(7),options).text,Weekly.EMPTY);const flat=entries().map(row=>({...row,patients:10,newPatients:0,sales:100000}));assert.equal(Weekly.analyze(flat,options).text,Weekly.EMPTY);const sparse=entries().map((row,index)=>({...row,patients:10,newPatients:0,sales:100000,checkups:index===29?1:0,clinical:{...row.clinical,xrays:0}}));assert.equal(Weekly.analyze(sparse,options).text,Weekly.EMPTY)});
test("夜間に毎日更新し直近7日と同じ発見は再保存しない",()=>{const night=Weekly.learnAtNight({entries:entries(),history:[],today:"2026-02-14",hour:20});assert.equal(night.saved,true);const next=Weekly.learnAtNight({entries:entries(),history:night.history,today:"2026-02-15",hour:20});assert.equal(next.saved,true);assert.equal(next.record.insights.some(item=>night.record.insights.some(previous=>previous.key===item.key)),false);assert.equal(Weekly.learnAtNight({entries:entries(),history:[],today:"2026-02-14",hour:17}).saved,false)});
test("weeklyLearningHistoryを維持し旧JSONには空配列を補う",()=>{const record={date:"2026-02-14",insights:[{key:"imaging:unit",text:"傾向でした。"}]},defaults={entries:[],learningHistory:[],weeklyLearningHistory:[],finance:{},clinic:{closedDates:[]},historical:{},settings:{},monthlyReports:{},memo:""};assert.deepEqual(Backup.normalizeBackup({entries:[],weeklyLearningHistory:[record]},defaults,"key").data.weeklyLearningHistory,[record]);assert.deepEqual(Backup.normalizeBackup({entries:[]},defaults,"key").data.weeklyLearningHistory,[])});
test("Today画面では最近の学習の後、異常検知カードの前に配置する",()=>{const html=require("node:fs").readFileSync(require.resolve("./index.html"),"utf8");assert.ok(html.indexOf("learningInsightCard")<html.indexOf("weeklyInsightCard"));assert.ok(html.indexOf("weeklyInsightCard")<html.indexOf("businessAnomalyCard"));assert.match(html,/Weekly Insights/);assert.match(html,/解析対象[\s\S]*7営業日[\s\S]*比較対象[\s\S]*30営業日/)});
